### ISSUE TITLE
Pass command line arguments to a Zenodo script

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#47]
I am enjoying using `showyourwork` (and it is removing a lot of the boiler plate that I had in hand-rolled reproducible papers) but I am struggling to fully take advantage of it as my workflow typically requires using the same script but was a series of different command line arguments and (as far as I can tell) this isn't possible in the current implementation.

**Comment by rodluger** [comment]
Interesting. I've been thinking about that a bit, and I think we could support that. Can you give me a sense of the kind of command line arguments you're providing to your script? The current way to do this (which will work as soon as I release the stuff on ``main`` in version ``0.1.28`` later today) is to include a bash script for each figure that calls python with the correct arguments, e.g.

**figures/figure1.sh:**
```bash
python script.py --fignum=1
```

**figures/figure2.sh:**
```bash
python script.py --fignum=2
```

**figures/script.py**
```python
import matplotlib.pyplot as plt
import argparse
...
fig.savefig("figure{}.pdf".format(fignum))
```

Then specify in ``showyourwork.yml`` how to run ``.sh`` scripts:

```yaml
scripts:
    sh:
        bash {script}
```

(check out the docs for version ``0.1.28``, which I'll release in the next few hours).

Would this strategy work for you?

Alternatively, we could think about overriding the ``\label`` command in LaTeX to allow for command line arguments, such as

```TeX
\begin{figure}
    \includegraphics{figures/figure1.pdf}
    \label[--fignum=1]{fig:script}
\end{figure}
```

We could alternatively override the ``figure`` environment to accept those arguments. I'd have to think more about this before implementing it though.

**Comment by arm61** [comment]
Possibly I can give an example from a snakemake workflow I was using previously which I would like to run locally and then pitch the `results` files up to Zenodo. 

Hopefully this code make sense (I have tried to modify the existing workflow to make it clearer). 

```
results = ['data/results_{i}.npz' for i in range(0, 10)]

rule analysis:
    input:
       # where my_analysis.py is some intensive analysis
        'code/my_analysis.py',
    output:
        ['data/results_{value}.npz'],
    run:
        shell('python {input[0]} {wildcards.value}')

rule plotting:
    input:
        'code/my_plot.py',
        results
    output:
       'figures/my_full_figure.py'
    run:
        shell('python {input[0]}')
```

So while both implementations that you mention could work, they might not fit perfectly with my ambition.

**Comment by rodluger** [comment]
I see! I understand the use case better now. I'm working on an example, will report back soon.

**Comment by rodluger** [comment]
@arm61 Here's roughly what I'm thinking. The basic idea is to automate the Zenodo upload/download and the tar/untarring of the results; the user handles the actual generation of the results in whatever way they'd like. So in ``showyourwork.yml``, specify this:

```yaml
zenodo:
  - src/data/results.tar.gz:
      title: Simulation results
      description: This is the result of a very expensive simulation.
      creators:
        - Luger, Rodrigo
      contents: &results
        - src/data/results_0.dat
        - src/data/results_1.dat
        - src/data/results_2.dat
        - src/data/results_3.dat
        - src/data/results_4.dat
        - src/data/results_5.dat
        - src/data/results_6.dat
        - src/data/results_7.dat
        - src/data/results_8.dat
        - src/data/results_9.dat

dependencies:
  src/figures/my_figure.py:
    *results
```

Basically I'd be extending``showyourwork`` to tar/untar Zenodo deposits. The ``&results`` and ``*results`` are just YAML anchor/aliases so we don't have to repeat the long list of files (read more about that [here](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd)).

Then, in the ``Snakefile``, provide a rule for generating the simulation results:

```
# All the results files generated by `run_simulation.py`
results = [f"src/data/results_{i}.dat" for i in range(0, 10)]

# Run an expensive simulation to generate a 
# results file for a given value in [0, 10)
rule analysis:
    input:
        "src/data/run_simulation.py"
    output:
        "src/data/results_{value}.dat"
    shell:
        "python {input[0]} {wildcards.value}"
```

When running locally, the simulation will be triggered to generate the `.dat` files whenever `run_simulation.py` changes. When running remotely, the results will *always* be downloaded from Zenodo.

How does this sound? Would that fix your issue?
