### ISSUE TITLE
Support wildcard syntax in showyourwork.yml

### ISSUE THREAD

**Issue by rodluger** [rodluger/showyourwork#49]
It would be useful to support wildcard syntax when specifying file dependencies or zenodo tarball contents in the ``showyourwork.yml`` file. Instead of

```yaml
dependencies:
    src/figures/foo.py:
        - src/data/results0.dat
        - src/data/results1.dat
        ...
        - src/data/results9.dat
```

we should support something like

```yaml
dependencies:
    src/figures/foo.py:
        - src/data/results{value,[0-9]}.dat
```

which is the same [wildcard syntax](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#wildcards) used by Snakemake.

**Comment by rodluger** [comment]
Now that I think of it, actually, it might not be this simple. Currently, users specify the *exact* list of file dependencies; regex syntax (as suggested above) would only tell ``showyourwork`` about *possible* file dependencies, which isn't enough information. In other words, the actual file names for the dependencies will in general be some subset of all the possible patterns matched by the wildcard regex, but *which ones* won't be known to ``showyourwork``, which will complicate the process of building the graph.

**Comment by rodluger** [comment]
@arm61 suggested Python ``for`` loop syntax for this in #47, which we could support if it's provided inside a string (and then ``eval`` it at runtime), but that seems pretty hacky. Other suggestions welcome!

**Comment by rodluger** [comment]
An alternative could be to support something similar to Azure for looping in YAML files: https://igeorgiev.eu/devops/azure-pipelines-use-each-loop/

**Comment by arm61** [comment]
I agree that the `eval` implementation is a bit on the hacky side. In my searching for something akin to python list comprehension in yaml I got a lot of hits on the Azure syntax you link above. However, does it allow for something like a `range` to be specified? 

Cards out I want to be able to loop over thousands of files so the range functionality is very desirable 😉.

**Comment by rodluger** [comment]
I figured you had more than just 10 datasets :)
I don't think the Azure syntax supports ``range`` but if we took that route we could certainly add support for it. Let me think about all this and get back to you. @dfm and @adrn, any thoughts on this?

**Comment by adrn** [comment]
Not sure this would work, and this might also be hacky, but maybe you could set up an "each" loop to iterate over output from a script? (see, e.g., under here https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#parameter-data-types)

**Comment by adrn** [comment]
Haha, yea I guess that's true...

**Comment by arm61** [comment]
Is there possibly a way that the range could be defined in the `Snakefile` and the variable that that is defined as used in the yaml? Implementing a custom YAML parser seems questionable.

**Comment by rodluger** [comment]
That's an interesting idea. We could maybe support something like

```yaml
dependencies:
    src/figures/foo.py:
        - {{ rules.analysis.output }}
```

where the ``Snakefile`` defines a rule like

```python
rule analysis:
    ...
    output:
        [f"src/data/results_{i}.dat" for i in range(0, 10)]
```

But I'd have to think about that some more.
