### ISSUE TITLE
Fails on files using spieman.cls

### ISSUE THREAD

**Issue by aditya-sengupta** [rodluger/showyourwork#52]
I was able to get showyourwork running locally with `make` on a .tex file using the "spieman" class (required for the SPIE Journals) by removing the line 

`\RequirePackage[hidelinks]{hyperref}`

and adding in the line

`\RequirePackage{graphicx}`

in `sywxml.sty` and `showyourwork.sty`. It seems like this is just a difference in which packages are preloaded in the .cls between SPIE and AASTeX, so it could be fixed if the scripts generating the .sty files could check for that. However, since they're remade with each run, I'm not able to change it manually.

**Comment by rodluger** [comment]
@aditya-sengupta This was fixed in version `v0.1.23` (see [here](https://github.com/rodluger/showyourwork/commit/353b3a420171776f3259bb9d7bdd96a3ed28a966#diff-4912c0fc6e31b9ace58270a5cba825afe0438e61070887d81df42b59533b7ccb)).

Which version of ``showyourwork`` do you currently have? If it's >= `v0.1.16`, you can just do

```
make update
```

at the root of your repo to bring it up to date. If you have an earlier version, you need to do

```
cd showyourwork
git fetch --all --tags
git checkout v0.1.30
```

to upgrade to the latest version (currently `v0.1.30`). Let me know if this works.

**Comment by aditya-sengupta** [comment]
`make` now works locally, but is failing in the github action: https://pastebin.com/xbkwMfqW

**Comment by rodluger** [comment]
Hmm, that's a very uninformative error message. Can you make sure you have

```yaml
verbose: true
```

in your ``showyourwork.yml``? Also, try resetting the remote build cache by bumping ``article-cache-number`` in ``.github/workflows/showyourwork.yml``:

```yaml
      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          article-cache-number: 1
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
```

Let me know what happens. In the meantime, I'm working on a feature to upload an artifact with complete build logs in case an action fails. I'll keep you posted.

**Comment by aditya-sengupta** [comment]
The error this time is a lot more straightforward, it can't find snakemake: https://pastebin.com/mAfvMpk3

**Comment by rodluger** [comment]
Very strange. One more thing: bump the conda cache as well:

```yaml
      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          article-cache-number: 1
          conda-cache-number: 1
        env:
          ZENODO_TOKEN: ${{ secrets.ZENODO_TOKEN }}
```
