### ISSUE TITLE
Problems with extracting from Zenodo tar when multiple figures depend on a given simulation dataset

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#63]
If you have something like the following `showyourwork.yml.jinja` file.
```
src/figures/figure_1: &figure_1_results
      {% for i in range(128) -%}
      - src/data/result_1_{{i}}.npz
      {% endfor %} 
src/figures/figures_2: &figure_2_results
      {% for var_1 in range(2) -%}
      {% for var_2 in range(128) -%}
      - src/data/result_{{var_1}}_{{var_2}}.npz
      {% endfor %} 
      - src/data/another_result_{{var_1}.npz
      {% endfor %} 
```
Where these results files have been created in some big simulation and uploaded to Zenodo. 
When running on CI, when the data is being untar (after download from Zenodo), the following error results.
```
Rules extract_src_data_figure_1_results_tar_gz and extract_src_data_figure_2_results_tar_gz are ambiguous for the file src/data/result_1_0.npz.
```
This seems to be due to the fact that both figures depend on the same files, however these are coming from different Zenodo records. Any ideas?

(p.s. sorry if what I am explaining is unclear I am trying to come up with a minimum failing version based on a more complex routine that I have).

**Comment by rodluger** [comment]
I don't have time to look over this in detail until tomorrow, but if the files have the same name and are coming from different Zenodo deposits, you should place them (and the tarball) in different subdirectories to prevent overwriting then -- and to resolve the ambiguity. Let me know if that helps.

**Comment by arm61** [comment]
The would massively increase the number of files no? i.e. in the above, the file `src/data/result_1_0.npz` is only created once but used in both figures.

**Comment by rodluger** [comment]
I guess I don't fully understand your setup. Is `src/data/result_1_0.npz` present in two different Zenodo deposits? That's what `showyourwork` seems to think: there are two different Zenodo tarballs it's unpacking, and the error occurs because it can't decide which of the two tarballs to unpack to generate each of the figures. Can you explain in a bit more detail what you're trying to do (and maybe show me the `zenodo:` section of your `yaml` file)?

**Comment by arm61** [comment]
Sorry I realised there was a typo in my original example code above (I have fixed it now changing the second `& figure_1_results` to `& figure_2_results `. The `zenodo:` section would be something like:

```
zenodo:
    - src/data/figure_1_results.tar.gz:
        sandbox: false
        token_name: ZENODO_TOKEN
        title: figure 1 results
        description: >-
            a description
        creators:
            - McCluskey, Andrew R.
        contents:
            * figure_1_results
    - src/data/figure_2_results:
        sandbox: false
        token_name: ZENODO_TOKEN
        title: figure 2 results 
        description: >-
            another description 
        creators:
            - McCluskey, Andrew R.
        contents:
            * figure_2_results
```
