### ISSUE TITLE
Github action worker running out of space

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#67]
My GitHub action fails when constructing the ArXiv tarball with the following error 
```
System.IO.IOException: No space left on device
``` 
This *appears* to be after all of the data downloaded from Zenodo is removed, but I am not exactly clear. 

I recognise this probably isn't a `showyourwork` problem (my untarred Zenodo data is > 18 Gb) but I am confused cause the Zenodo data seems to be removed.

Any thoughts?

**Comment by rodluger** [comment]
I think I know what the issue is. `showyourwork` automatically ignores datasets when uploading to Zenodo, but for tarballs it may only be ignoring the tarball itself (and still trying to tar up the contents of the tarball). I'll look into this today. In the meantime, you could set the `arxiv-tarball` option to `false` in `.github/workflows/showyourwork.yml`:

```
      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          arxiv-tarball: false
        ...
```

which will skip the tarball generation step.
